### ISSUE TITLE
Descripcion de autores

### ISSUE THREAD

**Issue by data-datum** [data-datum/ML_tidymodels#3]
En la pagina web 
https://ml-tidy-wibds.netlify.app/people/
cuando se entra a la descripcion de Patri, se lee la de Roxana. 
Comparar con https://conf20-intro-ml.netlify.app/people/

**Comment by anadiedrichs** [comment]
@data-datum subí datos actualizados de mi perfil y solucione el link al perfil de Patri. Portas los cambios a netlify ??

**Comment by anadiedrichs** [comment]
Buenas @data-datum ¿me pasarías en que sitio o ejemplo te basaste para construir el sitio? 
Hay un comportamiento raro en el apartado contactos que observo localmente en mi Pc. La primera a la que le hago click, es el perfil que se sigue cargando independientemente de a quien haga click  luego. 
Me ayudaría mucho si me pasas el ejemplo o ejemplos original en el que te basaste para encontrar la raíz del problema.
Gracias desde ya Roxi @data-datum

**Comment by anadiedrichs** [comment]
Comentarios acerca del issue y la solución en [este enlace](https://docs.google.com/document/d/11mO2q08Zxv0qBpTn8LrKhFjA9kgQMpZyBnS7_FVp-pI/edit?usp=sharing)
